---
- name: añadir puertos
  command: "{{ item }}"
  with_items:
    - firewall-cmd --zone=public --permanent --add-port=10250/tcp
    - firewall-cmd --zone=public --permanent --add-port=30000-32767/tcp  

- name: reload firewalld
  become: yes
  command: /usr/bin/systemctl reload firewalld

- name: unirse al cluster
  become: yes
  ignore_errors: True
  command: "{{ hostvars['master']['kubernetes_join_command'] }} --ignore-preflight-errors Swap"

